### ISSUE TITLE
Codemos keeps asking for access to my Github account, after denying access

### ISSUE THREAD

**Issue by zliebersbach** [Codemos-Inc/Codemos-Modern#177]
<img width="417" alt="image" src="https://github.com/Codemos-Inc/Codemos-Modern/assets/13294419/a50b5e09-db41-4704-8ba0-3fb3c57a87bc">

I do not want to give the theme access to my Github account, as I don't use that feature. Is there a way to get it to stop prompting me every time I launch VSCode?

Happy to contribute as well!

**Comment by EmrecanKaracayir** [comment]
I will examine the issue and try to correct it. That is not the intended behavior.

**Comment by EmrecanKaracayir** [comment]
A fix landed on main, will be released by v2.6.2. Thank you for reporting 😊.
