### ISSUE TITLE
Is there a way for disabling underlines?

### ISSUE THREAD

**Issue by RVFET** [Codemos-Inc/Codemos-Modern#184]
So many underlines (specifically in golang), makes reading the code way more challenging than it already is. Is there a way to disable those underlines? Perhaps a textmate trick or something?

![image](https://github.com/user-attachments/assets/ec9ead3f-27e3-4c3c-8327-e076b0bf2027)

**Comment by EmrecanKaracayir** [comment]
Yes there are a setting actually.

Go to **Settings/Extensions/Codemos Modern/Text Decorations/Underline** and untick the checkbox.

![image](https://github.com/user-attachments/assets/11c1719b-0e05-4f87-a5a8-6bfe4f1463e2)
